language: ruby

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - jruby
  - ruby-head

script: bundle exec rake test; bundle exec rake test # run twice to test the generator (thor scripts) via generated classes & tests
