language: ruby

matrix:
  allow_failures:
    - rvm: ree


rvm:
  - 2.2.1
  - 2.1.4
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-head
  - ruby-head
  - rbx

script: bundle exec rake test; bundle exec rake test # run twice to test generated classest & tests
