language: ruby

rvm:
  - 2.2.1
  - 2.1.4
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-head
  - jruby-head
  - ruby-head
  - ree

script: bundle exec rake test; bundle exec rake test # run twice to test generated tests :)
